language: go

go:
  - 1.6.x
  - 1.7.x
  - master

before_install:
  - go get github.com/golang/lint/golint

install:
  - cd webpush

  # golint returns a zero code regardless of errors. This prints out messages..
  - golint
  # .... this errors if any output is printed to stdout
  - test -z "$$(golint .)"

  - go vet
  - go test -v
