language: go

cache:
  directories:
    - node_modules
    - ~/.selenium-assistant

go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - master

before_script:
  - go get github.com/golang/lint/golint
  # Read more here: https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start || echo \"Unable to start virtual display.\""
  - sleep 3 # give xvfb some time to start

script:
  - cd webpush
  - golint -set_exit_status
  - go vet
  - go test -v
